require('core.plugin_config.autopairs')
-- require('core.plugin_config.gitsigns')
-- require('core.plugin_config.indent_blankline')
require('core.plugin_config.lsp_config')
require('core.plugin_config.treesitter')
