#!/bin/bash

for vim_path in 'after' 'autoload' 'bundle'; do
  if [ -d "/cygdrive/c/Users/Stan Angeloff/.vim/$vim_path" ]; then
    rm -Rf "/cygdrive/c/Users/Stan Angeloff/.vim/$vim_path"
  fi
  mkdir -p "/cygdrive/c/Users/Stan Angeloff/.vim/$vim_path"
  cp -Rf "/home/stan/.vim/$vim_path" "/cygdrive/c/Users/Stan Angeloff/.vim/"
done

for vim_path in 'backup' 'undo'; do
  mkdir -p "/cygdrive/c/Users/Stan Angeloff/.vim/$vim_path"
done

cp -f /home/stan/.vimrc /cygdrive/c/Users/Stan\ Angeloff/

