#!/usr/bin/env ruby

require 'fileutils'

git_bundles = [
  'git://github.com/ciaranm/detectindent.git',
  'git://github.com/godlygeek/csapprox.git',
  'git://github.com/godlygeek/tabular.git',
  'git://github.com/gregsexton/gitv.git',
  'git://github.com/juvenn/mustache.vim.git',
  'git://github.com/kchmck/vim-coffee-script.git',
  'git://github.com/leshill/vim-json.git',
  'git://github.com/mattn/zencoding-vim.git',
  'git://github.com/mexpolk/vim-taglist.git',
  'git://github.com/mileszs/ack.vim.git',
  'git://github.com/msanders/snipmate.vim.git',
  'git://github.com/othree/html5.vim.git',
  'git://github.com/pangloss/vim-javascript.git',
  'git://github.com/samsonw/vim-task.git',
  'git://github.com/scrooloose/nerdcommenter.git',
  'git://github.com/scrooloose/nerdtree.git',
  'git://github.com/scrooloose/syntastic.git',
  'git://github.com/sjl/gundo.vim.git',
  'git://github.com/StanAngeloff/vim-zend55.git',
  'git://github.com/tpope/vim-fugitive.git',
  'git://github.com/tpope/vim-git.git',
  'git://github.com/tpope/vim-haml.git',
  'git://github.com/tpope/vim-markdown.git',
  'git://github.com/tpope/vim-repeat.git',
  'git://github.com/tpope/vim-surround.git',
  'git://github.com/tpope/vim-unimpaired.git',
  'git://github.com/tsaleh/vim-supertab.git',
  'git://github.com/vim-scripts/Conque-Shell.git',
  'git://github.com/vim-scripts/easytags.vim.git',
  'git://github.com/vim-scripts/Gist.vim.git',
  'git://github.com/vim-scripts/grep.vim.git',
  'git://github.com/vim-scripts/IndexedSearch.git',
  'git://github.com/vim-scripts/php.vim--Garvin.git',
  'git://github.com/vim-scripts/phpcomplete.vim.git',
  'git://github.com/vim-scripts/phpfolding.vim.git',
  'git://github.com/vim-scripts/PHP-correct-Indenting.git',
  'git://github.com/vim-scripts/session.vim--Odding.git',
  'git://github.com/vim-scripts/shell.vim--Odding.git',
  'git://git.wincent.com/command-t.git'
]

bundles_dir = File.expand_path(File.join(File.dirname(__FILE__), 'bundle'))
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  if File.exists?(dir)
    puts "[UPDATING] #{dir} (from '#{url}')"
    FileUtils.cd(dir)
    `git pull --force --verbose --progress`
    FileUtils.cd(bundles_dir)
  else
    puts "[INSTALLING] #{dir} (from '#{url}')"
    `git clone --verbose --progress #{url} #{dir}`
  end
end
