#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/godlygeek/csapprox.git",
  "git://github.com/mexpolk/vim-taglist.git",
  "git://github.com/kchmck/vim-coffee-script.git",
  "git://github.com/leshill/vim-json.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/Townk/vim-autoclose.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/tsaleh/vim-tcomment.git",
  "git://github.com/StanAngeloff/vim-zend55.git",
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["gist",          "12732", "plugin"],
  ["grep",          "7645",  "plugin"],
]

vim_org_archives = [
  ["php", "http://www.vim.org/scripts/download_script.php?src_id=12772", "syntax"],
]

require 'fileutils'
require 'open-uri'
require 'tempfile'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

vim_org_archives.each do |name, download_url, script_type|
  puts "  Downloading #{name}"
  download_file = Tempfile.new(name)
  File.open(download_file.path, "w") do |file|
    file << open(download_url).read
  end
  local_file = File.join(name, script_type)
  FileUtils.mkdir_p(local_file)
  `tar zxf "#{download_file.path}" -C "#{local_file}"`
  File.delete(download_file.path)
end
